=== ServerlessOpsIO/aws-dns-management/data/src/handlers/RegisterDnsZone/output.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Status": {
      "type": "string"
    },
    "StackId": {
      "type": "string"
    },
    "RequestId": {
      "type": "string"
    },
    "LogicalResourceId": {
      "type": "string"
    },
    "PhysicalResourceId": {
      "type": "string"
    }
  },
  "required": [
    "LogicalResourceId",
    "PhysicalResourceId",
    "RequestId",
    "StackId",
    "Status"
  ]
}

=== ServerlessOpsIO/aws-dns-management/data/src/handlers/RegisterDnsZone/output.json
{
  "Status" : "SUCCESS",
  "StackId" : "arn:aws:cloudformation:us-east-1:123456789012:stack/mystack/5b918d10-cd98-11ea-90d5-0a9cd3354c10",
  "RequestId" : "uniqueid for this update request",
  "LogicalResourceId" : "RegisterDnsZoneFunction",
  "PhysicalResourceId" : "stack-RegisterDnsZoneFunction-main"
}
